config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :nominations

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
end

app/models/nomination.rb
class Nomination < ActiveRecord::Base

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :candidate
  belongs_to :nomination

  validates :candidate, presence: true
  validates :nomination, presence: true
  validates :ip, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  def index
    @nominations = Nomination.all
  end

  def show
    @nomination = Nomination.find(params[:id])
  end

  def new
    @nomination = Nomination.new
  end

  def create
    if @nomination.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

  private
  def nomination_params
    params.require(:nomination).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Номинации", nominations_path %>
<%= yield %>

</body>
</html>

app/views/nominations/delete.html.erb
<h1>Nominations#delete</h1>
<p>Find me in app/views/nominations/delete.html.erb</p>

app/views/nominations/edit.html.erb
<h1>Nominations#edit</h1>
<p>Find me in app/views/nominations/edit.html.erb</p>

app/views/nominations/index.html.erb
<h3>Список номинаций</h3>
<ul>
<% @nominations.each do |nomination| %>
    <li><%= link_to nomination.title, nomination_path(1) %></li>
<% end %>
</ul>

app/views/nominations/new.html.erb
<h3>Добавить номинацию</h3>

<%= form_for @nomination do |f| %>
    <p>
        <%= f.label :title, "Заголовок" %><br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description, "Описание" %><br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit "Сохранить" %>
    </p>
<% end %>

app/views/nominations/show.html.erb
<h3>Номинация: <%= @nomination.title %></h3>
<p>
   <%= @nomination.description %> 
</p>

app/views/nominations/update.html.erb
<h1>Nominations#update</h1>
<p>Find me in app/views/nominations/update.html.erb</p>